#!/usr/bin/env bash
# ─── Regenerate scripts/report-fonts.js (embedded PDF typefaces) ──────────────
# Downloads the OFL variable fonts, instances them to the weights the report uses,
# subsets to the report's glyph set (Basic Latin + the symbols used as HTML
# entities, INCLUDING the naira sign ₦ U+20A6, with the 'tnum' tabular-figure
# feature retained), and inlines each face as base64 woff2 into report-fonts.js.
#
# Display + body -> IBM Plex Sans   ("TIS Sans",  weights 400/500/600/700)
# Mono / figures  -> IBM Plex Mono  ("TIS Mono",  weights 400/500/600)
#   (Stage 9 — repoints the PDF onto one Plex superfamily; drops Inter and
#   Source Serif 4, self-hosted since Stage 0/5 respectively, which the PDF
#   never actually consumed.)
#
# Requires: python3 with fonttools + brotli, curl, node.
#   python3 -m pip install --user fonttools brotli
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/Library/Python/3.9/bin:$PATH"

TMP="$(mktemp -d)"
OUT="$TMP/out"; mkdir -p "$OUT"
UNI="U+0020-007E,U+00A0,U+00B1,U+00B7,U+00D7,U+0394,U+2013,U+2014,U+2018,U+2019,U+2026,U+2192,U+2194,U+2212,U+20A6,U+2713,U+25B6,U+26A0"

curl -sL -m 60 -o "$TMP/PlexSans.ttf" "https://github.com/google/fonts/raw/main/ofl/ibmplexsans/IBMPlexSans%5Bwdth,wght%5D.ttf"
# IBM Plex Mono ships as static per-weight files in google/fonts (no variable
# wght axis), unlike Plex Sans — so it skips the instancer step.
curl -sL -m 60 -o "$TMP/PlexMono-400.ttf" "https://github.com/google/fonts/raw/main/ofl/ibmplexmono/IBMPlexMono-Regular.ttf"
curl -sL -m 60 -o "$TMP/PlexMono-500.ttf" "https://github.com/google/fonts/raw/main/ofl/ibmplexmono/IBMPlexMono-Medium.ttf"
curl -sL -m 60 -o "$TMP/PlexMono-600.ttf" "https://github.com/google/fonts/raw/main/ofl/ibmplexmono/IBMPlexMono-SemiBold.ttf"

build() { # src wght wdth outname
  python3 -m fontTools.varLib.instancer "$1" wght=$2 wdth=$3 -o "$TMP/_inst.ttf" >/dev/null
  python3 -m fontTools.subset "$TMP/_inst.ttf" --unicodes="$UNI" --layout-features='*' \
    --flavor=woff2 --output-file="$OUT/$4" --no-hinting --desubroutinize >/dev/null
}
buildStatic() { # src outname  (no variable axes to instance)
  python3 -m fontTools.subset "$1" --unicodes="$UNI" --layout-features='*' \
    --flavor=woff2 --output-file="$OUT/$2" --no-hinting --desubroutinize >/dev/null
}
build "$TMP/PlexSans.ttf" 400 100 plexsans-400.woff2
build "$TMP/PlexSans.ttf" 500 100 plexsans-500.woff2
build "$TMP/PlexSans.ttf" 600 100 plexsans-600.woff2
build "$TMP/PlexSans.ttf" 700 100 plexsans-700.woff2
buildStatic "$TMP/PlexMono-400.ttf" plexmono-400.woff2
buildStatic "$TMP/PlexMono-500.ttf" plexmono-500.woff2
buildStatic "$TMP/PlexMono-600.ttf" plexmono-600.woff2

node - "$OUT" <<'JS'
const fs=require('fs'),path=require('path');const dir=process.argv[2];
const b64=f=>fs.readFileSync(path.join(dir,f)).toString('base64');
const faces=[['TIS Sans',400,'plexsans-400.woff2'],['TIS Sans',500,'plexsans-500.woff2'],
  ['TIS Sans',600,'plexsans-600.woff2'],['TIS Sans',700,'plexsans-700.woff2'],
  ['TIS Mono',400,'plexmono-400.woff2'],['TIS Mono',500,'plexmono-500.woff2'],
  ['TIS Mono',600,'plexmono-600.woff2']];
const css=faces.map(([fam,w,file])=>`@font-face{font-family:'${fam}';font-style:normal;font-weight:${w};font-display:swap;src:url(data:font/woff2;base64,${b64(file)}) format('woff2');}`).join('\n');
const header=`'use strict';
// ─── Embedded report typefaces (self-contained, no CDN, host-independent) ─────
// Generated by scripts/build-report-fonts.sh — IBM Plex Sans (display + body,
// "TIS Sans") + IBM Plex Mono (tabular figures/mono, "TIS Mono") — one Plex
// superfamily (Stage 9; replaces the earlier Inter + Source Serif 4 pairing),
// OFL-licensed, instanced to the weights used and subset to the report's glyph
// set (incl. ₦ U+20A6 and tabular figures 'tnum'). Each face is base64 woff2
// inlined straight into the print stylesheet so the PDF renders byte-identically
// on any machine regardless of installed fonts. Distinct family names
// ('TIS Sans'/'TIS Mono') guarantee these embedded faces are used, never a
// same-named host install.
// To regenerate: see scripts/build-report-fonts.sh.
`;
fs.writeFileSync('scripts/report-fonts.js',header+'\nconst FONT_FACE_CSS = `'+css+'`;\n\nmodule.exports = { FONT_FACE_CSS };\n');
console.log('wrote scripts/report-fonts.js');
JS
rm -rf "$TMP"
