#!/usr/bin/env bash
# ─── Regenerate scripts/report-fonts.js (embedded PDF typefaces) ──────────────
# Downloads the OFL variable fonts, instances them to the weights the report uses,
# subsets to the report's glyph set (Basic Latin + the symbols used as HTML
# entities, INCLUDING the naira sign ₦ U+20A6, with the 'tnum' tabular-figure
# feature retained), and inlines each face as base64 woff2 into report-fonts.js.
#
# Body / tables  -> Inter            ("TIS Sans",  weights 400/500/600/700)
# Cover + heads  -> Source Serif 4   ("TIS Serif", weight 600)
#
# Requires: python3 with fonttools + brotli, curl, node.
#   python3 -m pip install --user fonttools brotli
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/Library/Python/3.9/bin:$PATH"

TMP="$(mktemp -d)"
OUT="$TMP/out"; mkdir -p "$OUT"
UNI="U+0020-007E,U+00A0,U+00B1,U+00B7,U+00D7,U+0394,U+2013,U+2014,U+2018,U+2019,U+2026,U+2192,U+2194,U+2212,U+20A6,U+2713,U+25B6,U+26A0"

curl -sL -m 60 -o "$TMP/Inter.ttf"        "https://github.com/google/fonts/raw/main/ofl/inter/Inter%5Bopsz,wght%5D.ttf"
curl -sL -m 60 -o "$TMP/SourceSerif4.ttf" "https://github.com/google/fonts/raw/main/ofl/sourceserif4/SourceSerif4%5Bopsz,wght%5D.ttf"

build() { # src wght opsz outname
  python3 -m fontTools.varLib.instancer "$1" wght=$2 opsz=$3 -o "$TMP/_inst.ttf" >/dev/null
  python3 -m fontTools.subset "$TMP/_inst.ttf" --unicodes="$UNI" --layout-features='*' \
    --flavor=woff2 --output-file="$OUT/$4" --no-hinting --desubroutinize >/dev/null
}
build "$TMP/Inter.ttf"        400 14 inter-400.woff2
build "$TMP/Inter.ttf"        500 14 inter-500.woff2
build "$TMP/Inter.ttf"        600 14 inter-600.woff2
build "$TMP/Inter.ttf"        700 14 inter-700.woff2
build "$TMP/SourceSerif4.ttf" 600 18 serif-600.woff2

node - "$OUT" <<'JS'
const fs=require('fs'),path=require('path');const dir=process.argv[2];
const b64=f=>fs.readFileSync(path.join(dir,f)).toString('base64');
const faces=[['TIS Sans',400,'inter-400.woff2'],['TIS Sans',500,'inter-500.woff2'],
  ['TIS Sans',600,'inter-600.woff2'],['TIS Sans',700,'inter-700.woff2'],
  ['TIS Serif',600,'serif-600.woff2']];
const css=faces.map(([fam,w,file])=>`@font-face{font-family:'${fam}';font-style:normal;font-weight:${w};font-display:swap;src:url(data:font/woff2;base64,${b64(file)}) format('woff2');}`).join('\n');
const header=`'use strict';
// ─── Embedded report typefaces (self-contained, no CDN, host-independent) ─────
// Generated by scripts/build-report-fonts.sh — Inter (body/tables, "TIS Sans") +
// Source Serif 4 (cover title + section headers, "TIS Serif"), OFL-licensed,
// instanced to the weights used and subset to the report's glyph set (incl. ₦
// U+20A6 and tabular figures 'tnum'). Each face is base64 woff2 inlined straight
// into the print stylesheet so the PDF renders byte-identically on any machine
// regardless of installed fonts. Distinct family names ('TIS Sans'/'TIS Serif')
// guarantee these embedded faces are used, never a same-named host install.
// To regenerate: see scripts/build-report-fonts.sh.
`;
fs.writeFileSync('scripts/report-fonts.js',header+'\nconst FONT_FACE_CSS = `'+css+'`;\n\nmodule.exports = { FONT_FACE_CSS };\n');
console.log('wrote scripts/report-fonts.js');
JS
rm -rf "$TMP"
